### ISSUE TITLE
有偿咨询

### ISSUE THREAD

**Issue by lzbushicai** [zhyzhyzhy123/zhyzhyzhy123.github.io#1]
嗨，你好呀？我在monoscene上看到了你也训练了自己的数据集，我自己处于无基础指导有限的状况，请问我可以有偿咨询一些有关训练自己数据集的问题吗？如果方便的话，我的邮箱是liuzhenccc@163.com，微信是17771324335，谢谢！！！！

**Comment by zhyzhyzhy123** [comment]
没事我们一起交流，我加你了
